### PR TITLE
Fix/disallow filename characters

### LINKED ISSUE #370: Disallow characters in filenames
For cross-os compatibility reasons we would like to not allow filenames with the following characters:

`\/:*?"<>|`

Also no control characters or null.

See also neicnordic/sda-cli#185

Return 406.

[see discussion here.](https://superuser.com/questions/358855/what-characters-are-safe-in-cross-platform-file-names-for-linux-windows-and-os)

And deploy and test after deploy!

### PR DESCRIPTION
**Pull request by aaperis**
This PR prevents potential filepath naming problems that may arise due to cross-platform incompatibilities.

The procedure implemented is as follows:
- a filepath is first checked whether it contains both "/" and "\\". If yes, the request is rejected. This prevents generating erroneous folder structure in the next step.
- all file separators in the filepath are changed to the host's OS convention
- the resulting filepath is checked against a regex set of characters that we wish to disallow and if a hit is found the request is rejected.
In case of a rejection, `proxy` returns a 406 error response to the client and prints debug logs with details on the disallowed characters found in the filepath. Testsuite is updated, too.

The fix was tested for the case when `proxy` runs in linux and an s3 client (s3cmd, sda-cli) runs in either linux or windows. Not tested for mac but hopefully it behaves like linux ;-).

P.S. following standup discussion, spaces in filenames are allowed (along with the majority of unicode).

Closes #370

### CODE REVIEW

File: helper/helper.go [hunk 1]
```diff
@@ -363,3 +366,27 @@ func TLScertToFile(filename string, derBytes []byte) error {
...
+
+// FormatUploadFilePath ensures that path separators are "/", and returns error if the
+// filepath contains a disallowed character matched with regex
+func FormatUploadFilePath(filePath string) (string, error) {
+
+	// Check for mixed "\" and "/" in filepath. Stop and throw an error if true so that
+	// we do not end up with unintended folder structure when applying ToSlash later on
+	if strings.Contains(filePath, "\\") && strings.Contains(filePath, "/") {
+		return filePath, fmt.Errorf("filepath contains mixed '\\' and '/' characters")
+	}
```
Comment (jbygdell) [inline helper/helper.go:378]:
```suggestion
	outPath := strings.ReplaceAll(filePath, "\\", "/")
```

If we can assume that file paths with double backslashes `\\` originate from a windows machine we could simplify it like this.

File: helper/helper_test.go [hunk 2]
```diff
@@ -70,3 +72,39 @@ func TestCreateECToken(t *testing.T) {
...
+	uploadPath, err = FormatUploadFilePath(testPath)
+	if runtime.GOOS == "windows" {
+		// this is expected to work on windows
+		assert.Equal(t, unixPath, uploadPath)
+		assert.NoError(t, err)
+	} else {
+		// this is expected to fail on linux/mac
+		assert.ErrorContains(t, err, "filepath contains disallowed characters: \\, \\")
+
+	}
```
Comment (jbygdell) [inline helper/helper_test.go:95]:
```suggestion
	testPath = "a\\b\\c.c4gh"
	uploadPath, err = FormatUploadFilePath(testPath)
	assert.ErrorContains(t, err, "filepath contains disallowed characters: \\, \\")
```

That test is only viable if the test suite is executed on a windows machine.

File: helper/helper_test.go [hunk 3]
```diff
@@ -70,3 +72,39 @@ func TestCreateECToken(t *testing.T) {
...
+	assert.EqualError(t, err, "filepath contains mixed '\\' and '/' characters")
+
+	// no mixed "\" and "/" but not allowed
+	weirdPath = `dq\sw:*?"<>|\t\sdf.c4gh`
+	_, err = FormatUploadFilePath(weirdPath)
+	if runtime.GOOS == "windows" {
+		assert.EqualError(t, err, "filepath contains disallowed characters: :, *, ?, \", <, >, |")
+	} else {
+		assert.EqualError(t, err, "filepath contains disallowed characters: \\, :, *, ?, \", <, >, |, \\, \\")
+	}
```
Comment (jbygdell) [inline helper/helper_test.go:109]:
```suggestion
	// no mixed "\" and "/" but not allowed
	weirdPath = `dq\sw:*?"<>|\t\sdf.c4gh`
	_, err = FormatUploadFilePath(weirdPath)
	assert.EqualError(t, err, "filepath contains disallowed characters: \\, :, *, ?, \", <, >, |, \\, \\")
```

That test is only viable if the test suite is executed on a windows machine.

**Review by jbygdell — CHANGES_REQUESTED** [review]

**Comment by pontus** [comment]
Does the library unescape the URI before handing it to the handler functions?

File: helper/helper_test.go (hunk 2 above)
Comment (aaperis) [reply helper/helper_test.go:95]: Yes, indeed. However I added it there because,

1. I expect that someone may wish to run the testsuite from a windows machine
2. In a way, this does provide a way to test a scenario where a windows client interacts with the `proxy` since the different   behavior documented here originates from the way `testPath` is interpreted depending on the OS thus simulating the s3 client's host OS.
3. I think keeping these tests is a good way to document these differences between win and linux

File: helper/helper_test.go (hunk 3 above)
Comment (aaperis) [reply helper/helper_test.go:109]: See answer above :-)

**Comment by aaperis** [comment]
> Does the library unescape the URI before handing it to the handler functions?

Which library and URI are you referring to?

**Comment by pontus** [comment]
> > Does the library unescape the URI before handing it to the handler functions?
> 
> Which library and URI are you referring to?

The golang provided net/http and the incoming URI.

Another formulation of this is essentially - if the client sends a name such as `something%5csomethingelse`, what will happen?

File: helper/helper.go (hunk 1 above)
Comment (aaperis) [reply helper/helper.go:378]: I see the reasoning but I do not agree to change all backslashes automatically to slashes  since this can potentially cause a mess in the folder structure.
The above looks for paths of the form `path1\path2/path2\file.c4gh` etc. So it basically mitigates the recent problem we had with the `-targetDir` flag which was fixed in `sda-cli` but still it's worth to keep a check just in case this problem resurfaces in some other way. The suggested simplification is basically done at line 381 (see comment above).

File: helper/helper.go [hunk 4]
```diff
@@ -363,3 +366,27 @@ func TLScertToFile(filename string, derBytes []byte) error {
...
+
+	// make path separators os compatible
+	outPath := filepath.ToSlash(filePath)
```
[the remark this answers is not in the document]
Comment (aaperis) [reply helper/helper.go:381]: Given a filepath `path1\path2\path2` (coming from a client running in windows), the above line should change it to `path1/path2/path3` which is the desired behavior.

File: helper/helper.go (hunk 1 above)
Comment (pontus) [reply helper/helper.go:378]: Can you clarify the use case for having backslashes in the object name?

File: proxy.go [hunk 5]
```diff
@@ -87,6 +88,12 @@ func (p *Proxy) notAllowedResponse(w http.ResponseWriter, _ *http.Request) {
 	w.WriteHeader(403)
 }
 
+func (p *Proxy) notAcceptableResponse(w http.ResponseWriter, _ *http.Request) {
+	log.Debug("not acceptable response")
+	// http.Error(w, "request not acceptable", 406)
+	w.WriteHeader(406)
+}
+
```
[the remark this answers is not in the document]
Comment (aaperis) [reply proxy.go]: Good catch, this shouldn't have been there. Now removed.

File: helper/helper.go (hunk 1 above)
Comment (aaperis) [reply helper/helper.go:378]: I wouldn't say it is a use case but rather a situation we wish to avoid happening again in the future.

Comment (pontus) [reply helper/helper.go:378]: It seems to me the safest way to avoid the recent issues would be to remove all backslashes from the names -  I really don't see when one would want to not delete them.

File: helper/helper.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (jbygdell) [reply helper/helper.go:381]: It will not do that since the S3proxy is *not* running on windows.

```go
// ToSlash returns the result of replacing each separator character
// in path with a slash ('/') character. Multiple separators are
// replaced by multiple slashes.
func ToSlash(path string) string {
	if Separator == '/' {
		return path
	}
	return strings.ReplaceAll(path, string(Separator), "/")
}
```
`Separator` is the `os.PathSeparator` so on a linux machine it will just return the string as it is.

[the remark this answers is not in the document]
Comment (aaperis) [reply helper/helper.go:381]: yep, I got stuck in a loop. Now I see how running the unitests in windows was a bad idea! I now also get the comments on the unitests below. I will fix this.

File: helper/helper.go (hunk 1 above)
Comment (aaperis) [reply helper/helper.go:378]: I agree, however I would prefer not to interfere with the filepath by deleting/renaming backslashes automatically. So, for now I would suggest we keep the `regex` rule where if a backslash is found the request is rejected.

**Comment by aaperis** [comment]
> > > Does the library unescape the URI before handing it to the handler functions?
> > 
> > 
> > Which library and URI are you referring to?
> 
> The golang provided net/http and the incoming URI.
> 
> Another formulation of this is essentially - if the client sends a name such as `something%5csomethingelse`, what will happen?

Great point. As far as I [see](https://pkg.go.dev/net/url#URL.Path), the `path` from the URI is [unescaped](https://github.com/neicnordic/sda-s3proxy/blob/c25f1175656a30cc5b96ce4d56b26686d3a38cb4/proxy.go#L108). So, there is a potential mixup there, but I do not see how this can be mitigated on the proxy side. 
Anything that slips through should be caught eventually when validating the filepaths in the xmls against the files in the inbox before ingestion starts.

File: proxy.go [hunk 6]
```diff
@@ -87,6 +88,11 @@ func (p *Proxy) notAllowedResponse(w http.ResponseWriter, _ *http.Request) {
 	w.WriteHeader(403)
 }
 
+func (p *Proxy) notAcceptableResponse(w http.ResponseWriter, _ *http.Request) {
+	log.Debug("not acceptable response")
+	w.WriteHeader(406)
```
Comment (norling) [inline proxy.go:93]: using the http constant makes it more readable! :) 
```suggestion
	w.WriteHeader(http.StatusNotAcceptable)
```

File: proxy.go [hunk 7]
```diff
@@ -105,7 +111,16 @@ func (p *Proxy) allowedResponse(w http.ResponseWriter, r *http.Request) {
 	p.prependBucketToHostPath(r)
 
 	username := fmt.Sprintf("%v", claims["sub"])
-	filepath := strings.Replace(r.URL.Path, "/"+p.s3.bucket+"/", "", 1)
+	rawFilepath := strings.Replace(r.URL.Path, "/"+p.s3.bucket+"/", "", 1)
+
+	filepath, err := helper.FormatUploadFilePath(rawFilepath)
+	if err != nil {
+		log.Debugf(err.Error())
+		p.notAcceptableResponse(w, r)
```
Comment (norling) [inline proxy.go:119]: since this function is basically just one line - I'd prefer to just write the header directly instead of having an extra function.

File: proxy_test.go [hunk 8]
```diff
@@ -310,6 +310,16 @@ func (suite *ProxyTests) TestServeHTTP_allowed() {
...
 	assert.Equal(suite.T(), 200, w.Result().StatusCode)
 	assert.Equal(suite.T(), true, suite.fakeServer.PingedAndRestore())
+
+	// Filenames with platform incompatible characters are disallowed
+	// not checked in TestServeHTTP_allowed() because we look for a non 403 response
+	r.Method = "PUT"
+	r.URL, _ = url.Parse("/username/fi|le")
+	w = httptest.NewRecorder()
+	proxy.ServeHTTP(w, r)
+	assert.Equal(suite.T(), 406, w.Result().StatusCode)
```
Comment (norling) [inline proxy_test.go:320]: you could use `http.StatusNotAcceptable` instead of `406` here as well for readability, but might be a case for testing with the integer code as well.

**Review by norling — APPROVED** [review]
Some small stuff you might wanna look at, but looks good in general! :)

File: helper/helper.go [hunk 9]
```diff
@@ -363,3 +366,27 @@ func TLScertToFile(filename string, derBytes []byte) error {
...
+func FormatUploadFilePath(filePath string) (string, error) {
+
+	// Check for mixed "\" and "/" in filepath. Stop and throw an error if true so that
+	// we do not end up with unintended folder structure when applying ReplaceAll below
+	if strings.Contains(filePath, "\\") && strings.Contains(filePath, "/") {
+		return filePath, fmt.Errorf("filepath contains mixed '\\' and '/' characters")
+	}
+
+	// make any windows path separators linux compatible
+	outPath := strings.ReplaceAll(filePath, "\\", "/")
```
[the remark this answers is not in the document]
Comment (jbygdell) [reply helper/helper.go:381]: yes, but that one only converts `os.PathSeparator` to `/`
Here we have a specific case with escaped backslashes that needs to be converted.

File: proxy.go (hunk 7 above)
Comment (aaperis) [reply proxy.go:119]: I see the reasoning, I only chose to write it this way because all header responses in the `proxy` are done with one line functions, too. So this keeps the code consistent imo :)

File: helper/helper.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (aaperis) [reply helper/helper.go:381]: Yeah I thought so too but, it turns out `ToSlash` is not a good choice here since we have the case where `proxy` always runs in linux but s3clients that make incoming requests run on a host OS that is unknown to `proxy`.

File: proxy.go (hunk 6 above)
Comment (aaperis) [reply proxy.go]: Good point! Done.

File: proxy.go [hunk 10]
```diff
@@ -87,6 +88,11 @@ func (p *Proxy) notAllowedResponse(w http.ResponseWriter, _ *http.Request) {
 	w.WriteHeader(403)
 }
 
+func (p *Proxy) notAcceptableResponse(w http.ResponseWriter, _ *http.Request) {
+	log.Debug("not acceptable response")
+	w.WriteHeader(406)
+}
+
```
[the remark this answers is not in the document]
Comment (aaperis) [reply proxy.go]: This is intended to be a rather generic debug message like the other response functions do (e.g. see line 91 in `proxy.go`). 
example of debug output:
```
{"level":"info","msg":"User: dummy, Request type PUT, Path: /test/dummy/csa/sq?/data_file","time":"2023-04-20T11:51:56Z"}
{"level":"debug","msg":"filepath contains disallowed characters: ?","time":"2023-04-20T11:51:56Z"}
{"level":"debug","msg":"not acceptable response","time":"2023-04-20T11:51:56Z"}
```
There are two debug messages but not identical, the first one gives the explicit problem and the one below the response status . I can combine them in two but the way it is now the function above is reusable and in addition I think the debug messages are more informative.

File: proxy.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (aaperis) [reply proxy.go:118]: see above

File: proxy.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (aaperis) [reply proxy.go]: I removed the function and moved the `WriteHeader` in the main body.

File: proxy.go (hunk 7 above)
Comment (aaperis) [reply proxy.go]: I managed to overcome my consistency constraints, so now this is done.

File: helper/helper.go [hunk 11]
```diff
@@ -363,3 +366,27 @@ func TLScertToFile(filename string, derBytes []byte) error {
...
+
+// FormatUploadFilePath ensures that path separators are "/", and returns error if the
+// filepath contains a disallowed character matched with regex
+func FormatUploadFilePath(filePath string) (string, error) {
+
+	// Check for mixed "\" and "/" in filepath. Stop and throw an error if true so that
+	// we do not end up with unintended folder structure when applying ReplaceAll below
+	if strings.Contains(filePath, "\\") && strings.Contains(filePath, "/") {
+		return filePath, fmt.Errorf("filepath contains mixed '\\' and '/' characters")
+	}
```
Comment (jbygdell) [inline helper/helper.go:378]: This might be unnecessary in the end, but it will require manual testing to validate since `/` actually is a valid separator on windows.

**Review by jbygdell — APPROVED** [review]

**Review by dbampalikis — APPROVED** [review]
