### PR TITLE
Fix regexp no hit panic

### LINKED ISSUE #148: regexp assumes hit
This line assumes a hit in the regexp (by immediately calling `[1]`), and will result in a `panic` if it doesn't match.
https://github.com/neicnordic/sda-s3proxy/blob/4d0794b61b95f031a9a91c62ee464604159a5455/userauth.go#L184

### PR DESCRIPTION
**Pull request by nanjiangshu**
This PR closes #148 

It returned an error message when there is no valid matches for the regexp and thus avoid panic exit. 

**additional comments**
I feel a bit awkward with repeated coding and one might use `if else` to replace `switch` to solve the repeated coding problem. If you think it is necessary, I can do a refactoring but I guess the gain is little.

### CODE REVIEW

**Review by jbygdell — CHANGES_REQUESTED** [review]
* This check only needs to be performed once.
* It will require a dedicated test case
* Make use of what the `iss` filed in the token actually is

File: userauth_test.go [hunk 1]
```diff
@@ -135,6 +135,17 @@ func TestUserTokenAuthenticator_ValidateSignature_RSA(t *testing.T) {
 	_, brokenToken2 := a.Authenticate(r)
 	assert.Equal(t, "broken token (claims are empty): map[]", brokenToken2.Error()[0:38])
 
+	// Bad issuer
+	basIss, err := helper.CreateRSAToken(prKeyParsed, "ES256", "JWT", helper.WrongTokenAlgClaims)
```
Comment (jbygdell) [inline userauth_test.go:139]:
```suggestion
	basIss, err := helper.CreateRSAToken(prKeyParsed, "RS256", "JWT", helper.WrongTokenAlgClaims)
```
wrong algorithm for this test block

**Review by jbygdell — CHANGES_REQUESTED** [review]
Clean up the commits, it should at most be 3.

**Review by dbampalikis — APPROVED** [review]
Looks good! Just rebase on master to be able to merge :)

**Review by aaperis — APPROVED** [review]

**Review by jbygdell — APPROVED** [review]
